### ISSUE TITLE
What is the user_id field is for?

### ISSUE THREAD

**Issue by salexfo** [projectestac/moodle-local_oauth#3]
Hi,
Thanks for developing and publishing the plugin. It saved us a lot of time :-)

Quick question: I can't understand what the "user_id' field is being used for under the plugins' configuration page. I didn't find an explicit mention of such a field in the OAuth 2 spec.

Thanks,
Alexander

**Comment by sarjona** [comment]
Hi Alexander!!

Thanks for your message. In our case, we're not using never this user_id (so its value it's always 0). 

We adapted the Oauth2 Library from https://github.com/bshaffer/oauth2-server-php and this field was there in a lot of functions (that's why we decided to put also in the plugin configuration page).

Best wishes,
Sara
